### ISSUE TITLE
MessageQueryDto.StatusName is in lowercase, resulting in no results returned

### ISSUE THREAD

**Issue by captmomo** [colinin/DotNetCore.CAP.Sqlite#3]
` public IList<MessageDto> Messages(MessageQueryDto queryDto)`

Hi,
For the dashboard, when I click to see "Succeeded" or "Failed" events, no messages are returned. I discovered it's because the statusName for the MessageQueryDto passed in is in lowercase, but in the database it is saved as titlecase.

**Comment by colinin** [comment]
I will review the code. Thank you for your comments

**Comment by colinin** [comment]
This error has been fixed and the relevant Nuget package has to wait for approval before it can be updated

**Comment by captmomo** [comment]
Thank you!

There was another error I forgot to mention. Sometimes, the connection is not yet open, then it tries to run a query, this throws a null reference exception. I solved it by included a `await connection.openAsync()` below the using.


```
            using (var connection = new SqliteConnection(_options.Value.ConnectionString))
            {
                await connection.OpenAsync();
                var reader = await connection.ExecuteReaderAsync(sql, sqlParam);
                await connection.OpenAsync();
                while (reader.Read())
                {
                    result.Add(new MediumMessage
                    {
                        DbId = reader.GetInt64(0).ToString(),
                        Origin = StringSerializer.DeSerialize(reader.GetString(3)),
                        Retries = reader.GetInt32(4),
                        Added = reader.GetDateTime(5)
                    });
                }
                return result;
            }
```

thanks again for creating this library! Really appreciate it!

**Comment by colinin** [comment]
As far as I know, Dapper does not need to show open connections. The error here is that DbReader is not released and a using block should be used

**Comment by colinin** [comment]
I will create complete unit tests to detect potential problems，thinks

**Comment by colinin** [comment]
The problem has been fixed and the unit test has passed. Thank you for your feedback

**Comment by captmomo** [comment]
Thanks, you’re right I went to look at the source code and dapper calls
openasync if the connection is closed. Wondered why that worked though.
Thanks again!

**Comment by colinin** [comment]
Microsoft has documented that when you use the IDataReader interface, you must display a call to the Close method

[Microsoft docs IDataReader.Close Method](https://docs.microsoft.com/en-us/dotnet/api/system.data.idatareader.close?view=netcore-3.1)
