### ISSUE TITLE
有定时清理功能吗

### ISSUE THREAD

**Issue by HengzheLi** [colinin/DotNetCore.CAP.Sqlite#4]
如题，用sqlite会定时自动清理数据库表的记录吗

**Comment by colinin** [comment]
清理过期消息是CAP的特性，持久层提供实现的API



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月12日(星期四) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [colinin/DotNetCore.CAP.Sqlite] 有定时清理功能吗 (#4)





 
如题，用sqlite会定时自动清理数据库表的记录吗
