### ISSUE TITLE
CapStorageMarkerService does not have parameter less constructor

### ISSUE THREAD

**Issue by BBanoth** [colinin/DotNetCore.CAP.Sqlite#5]
CapStorageMarkerService has only one constructor with parameter i.e. name.

An exception is thrown by the host while running the application.

Please add the respective code while registering the service.

Current Code : services.AddSingleton<CapStorageMarkerService>();
Code required: services.AddSingleton(new CapStorageMarkerService("Sqlite"));

**Comment by colinin** [comment]
I'll check here. thanks
