### ISSUE TITLE
Latest 7.1.0 Package targets DotNetCore.CAP v7.0.0 - even though release notes says it upgrades to 7.1.0

### ISSUE THREAD

**Issue by niklasfp** [colinin/DotNetCore.CAP.Sqlite#6]
Hi There, 

It seems like the latest DotNetCore.CAP.Sqlite v7.1.0 still targets DotNetCore.CAP v7.0.0.

https://github.com/colinin/DotNetCore.CAP.Sqlite/blob/bcb9282c05cf387d98f0004e67614ac630a60af3/src/DotNetCore.CAP.Sqlite/DotNetCore.CAP.Sqlite.csproj#L18

Updating to DotNetCore.CAP v7.0.0 requires some extra steps to implement some new interface methods for locks.

I've added those methods here: https://github.com/colinin/DotNetCore.CAP.Sqlite/compare/master...niklasfp:DotNetCore.CAP.Sqlite:master and can do pr if needed.
Note this change also updates other outdated packages.

**Comment by colinin** [comment]
Looks great. Can you support StorageLock?
https://github.com/dotnetcore/CAP/blob/662011336d779770725518950a9870a097c8c74c/src/DotNetCore.CAP/CAP.Options.cs#L128

**Comment by niklasfp** [comment]
I'll have a look at the other sql implementations in CAP and see if there is any ideas there 😉
But  it works fine the way I have it now, I just ignore the calls and return success.

**Comment by colinin** [comment]
fix in #7 

![1685585762898](https://github.com/colinin/DotNetCore.CAP.Sqlite/assets/35512826/cf134d8b-6d8a-4016-b90c-dacce059149c)
